/** Re-exports official IPL rules — use iplRules.ts for all auction logic */
export {
  TOTAL_PURSE,
  MAX_SQUAD_SIZE,
  MIN_SQUAD_SIZE,
  MAX_OVERSEAS,
  MAX_RETENTIONS,
  MAX_CAPPED_RETENTIONS,
  MAX_UNCAPPED_RETENTIONS,
  FLEX_MAX_CAPPED_RETENTIONS,
  FLEX_MAX_UNCAPPED_RETENTIONS,
  MIN_BASE_PRICE_LAKHS,
  RETENTION_COSTS_CAPPED,
  RETENTION_COST_UNCAPPED,
  RETENTION_SLOT_LABELS,
  TIMER_INITIAL,
  TIMER_BID_RESET,
  TIMER_MAX,
  RTM_TIMER,
  RETENTION_TIMER,
  ROUND2_DISCOUNT,
  SET_ORDER_PREFIXES,
  calculateBidIncrement,
  calculateNextBid,
  getBidIncrementLabel,
  isRetentionMode,
  isRtmAllowed,
  getInitialRtmCards,
  getOverseasBidCapLakhs,
  calculateRetentionCost,
  validateRetentions,
  validateFlexRetentions,
  calculateFlexRetentionCost,
  seededShuffle,
  formatPrice,
  sortSetKey,
  IPL_RULES_SUMMARY,
} from "./iplRules";
